config/routes.rb
Rails.application.routes.draw do
  
  resources :machines do
    resources :pictures, only: [:new, :create, :destroy]
  end

  get 'connecteds/destroy'
  devise_for :users
  resources :users, only: [:index, :edit, :update, :show, :destroy]
  resources :connecteds, only: :destroy
  resources :categories, only:[:new, :create]


  get 'emails/index'
  get 'pages/home'
  get 'pages/dashboard'

  get :search, controller: :pages


  resources :people do
    collection do
      get :import
      post :import
    end
  end
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :companies, concerns: :paginatable do
    collection do
      get :import
      post :import
    end
  end
  
  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
  end
  

  root to: "pages#home"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :connected, dependent: :destroy
  has_many :people, -> {distinct}, through: :connected
  has_many :phones, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, allow_nil: true, allow_blank: true

  belongs_to :user
  belongs_to :country, optional: true
  belongs_to :state, optional: true

  delegate :name, to: :country, prefix: true, allow_nil: true
  delegate :name, to: :state, prefix: true, allow_nil: true

  accepts_nested_attributes_for :people, allow_destroy: true, reject_if: proc { |attributes| attributes['first_name'].blank? }
  accepts_nested_attributes_for :connected, allow_destroy: true, reject_if: proc { |attributes| attributes['person_id'].blank? }
  accepts_nested_attributes_for :phones, allow_destroy: true, reject_if: proc { |attributes| attributes['phone_number'].blank? }

  mount_uploader :logo, ImageUploader

  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      country_id = Country.find_by(alpha2: "#{row["Country"]}").id if row["Country"].present?
      state = State.where(country_id: country_id).find_by(name: "#{row["State"]}").id if row["State"].present?
      company_attributes = Hash.new
      company_attributes = {id: row["Id"],
                            name: (row["Name"].mb_chars.downcase if row["Name"].present?), 
                            country_id: country_id, 
                            state_id: state, 
                            town: (row["Town"].mb_chars.downcase if row["Town"].present?) , 
                            address_line: (row["Address_line"].mb_chars.downcase if row["Address_line"].present?), 
                            zip: row["Zip"], 
                            email: row["Email"], 
                            url: row["Url"], 
                            user_id: 2,
                            source: ((row["Source"].mb_chars.downcase if row["Source"].present?) or "makinaTR"),
                            note: (row["Note"].mb_chars.downcase if row["Note"].present?),
                            invoice_title: (row["Invoice"].mab_chars.downcase if row["Invoice"].present?)
                          }
      puts company_attributes
      company = Company.where(id: row["Id"])
        if company.present?
          company.first.update_attributes!(company_attributes)
          puts "#{row["Name"].mb_chars.upcase} updated.."
        else
          puts "trying to create #{company.name}"
          Company.create!(company_attributes)
          puts "#{row["Name"].mb_chars.upcase} created.."
        end
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      column_names << 'person_ids'
      column_names << 'phones'
      names = column_names
      csv << names
      all.each do |company|
        row = company.attributes.values_at(*column_names)
        row << company.person_ids
        row << company.phones.to_ary
        csv << row
      end
    end
  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  respond_to :html, :json
  after_action :index_page_url, only: [:index]
  
  def import
    if params[:file].present?
      if Company.import(params[:file])
        redirect_to import_companies_path
        flash[:notice] = "Data from CSV file imported"
      else
        redirect_to import_companies_path
        flash[:error] = "There is a problem with your data" 
      end
    end
  end

  def index
    @search = Company.search(params[:q])
    @pagy, @companies = pagy(policy_scope(@search.result).order('created_at desc'))
    @companies_count  = policy_scope(@search.result).count
    def index_page_url
      session[:index_page_url] = URI(request.original_url || "" )
    end

    respond_to do |format|
      format.html
      format.csv {send_data Company.all.to_csv}
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.people.build
    @company.phones.build
    authorize @company
  end

  # GET /companies/1/edit
  def edit
    @company.people.build
  end


  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user = current_user
    authorize @company

    flash[:notice] = "Company was successfully created." if @company.save
    respond_with(@company)
    # Update of Person position if params position present after creating person object
    if @company.people.present?
      @company.connected.where(position: "Not Assigned").reverse.each_with_index do |connect, i|
        connect.update(position: params[:company][:people_attributes]["#{i}"][:person_position]) if params[:company][:people_attributes]["#{i}"][:person_position].present?
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    if logo_params[:remove_logo] == "1"
      @company.remove_logo!
      @company.save
    end
      
    flash[:notice] = "Company was successfully updated." if @company.update(company_params)
    respond_with(@company)
    
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    flash[:notice] = "Company was successfully destroyed."
    respond_with(@company)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
      authorize @company
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name,
                                      :email,
                                      :unsubscribe,
                                      :url,
                                      :logo,
                                      :remote_logo_url,
                                      :address_title, :country_id, :state_id, :town, :zip,:address_line,
                                      :note,
                                      :source,
                                      :invoice_title,
                                      people_attributes:[ :first_name,
                                                          :middle_name,
                                                          :last_name,
                                                          :_destroy,
                                                          :id,
                                                          :person_position,
                                                          :company,
                                                          :user_id,
                                                          emails_attributes: [:email,
                                                                              :id,
                                                                              :unsubscribe,
                                                                              :user_id
                                                                              ],
                                                          phones_attributes: [:id,
                                                                              :phone_type,
                                                                              :phone_number
                                                                              ]
                                                        ],
                                    connected_attributes: [:person_id, 
                                                           :position, 
                                                           :id, 
                                                           :_destroy
                                                        ],
                                    phones_attributes:    [:id,
                                                          :phone_type,
                                                          :phone_number,
                                                          :_destroy
                                                        ]
                                     )
    end
    
    def logo_params
      params.require(:company).permit(:remove_logo)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>

  <% flash.now[:error] = company.errors.full_messages.to_sentence if company.errors.any? %>

<div class="container">
  <div class="form-group">
    <div class="custom-file">
      <%= form.file_field :logo, class: "custom-file-input", id: "customFile"  %>
      <%= form.label "upload a logo", class: "custom-file-label", for: "customFile" %>
    </div>
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <%= form.label "Upload Remote", class: "input-group-text", id: "basic-addon3" %>
    </div>
      <%= form.text_field :remote_logo_url, class: "form-control",id:"basic-url" %>
  </div>

  <div class="form-check-inline">
    <%= image_tag(company.logo_url(:thumb)) if company.logo? %>
    <%= form.label "Remove Logo", class: "form-check-label mx-2", for:"remove_logo" if company.logo? %>
    <%= form.check_box :remove_logo, class: "form-check-input", id:"remove_logo" if company.logo? %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control" %>

    <%= form.label :invoice_title %>
    <%= form.text_area :invoice_title, class: "form-control" %>

    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>

    <%= form.label :note %>
    <%= form.text_area :note, class: "form-control" %>
    
    <%= form.label :email %>
    <div class="row">
      <div class="col-md-9 form-group">
      <%= form.text_field :email, :class => "form-control" %>
      </div>
      
      <div class="col-md-3 form-group">
      <div class="form-check-inline">
        <%= form.check_box :unsubscribe, class: "form-check-input" %>
        <%= form.label :unsubscribe, class: "form-check-label" %>
      </div>
      </div>
    </div>
  </div>
    
  <div class="card mb-2">
      <h4 class="card-header">Company Phones</h4>
    <div class="card-body">
      <%= form.nested_fields_for :phones, :phones do |p_form| %>
        <%= render partial: "phones/phone", locals: {p_form: p_form} %>
      <% end %>
    </div>
    <div class="card-footer">
    <%= form.add_nested_fields_link :phones, "Add Phone", class: "btn btn-outline-primary btn-sm"%>
    </div>
  </div>

  <div class="card mb-2"> 
    <h4 class="card-header">Company Address</h4>
    <div class="card-body">
    <%= form.label :address_title %>
    <%= form.select :address_title, ["Factory", "Office", "Showroom", "Headquarters", "Branch", "Other" ] ,{prompt:"Choose..", include_blank: true},  {class: "form-control"} %>

      
    <%= form.label :country_id %>
    <%= form.collection_select :country_id, Country.order(:name), :id, :name,{prompt: "Choose..", include_blank: true}, {class:"chosen-select", data: {dynamic_selectable_url: dynamic_select_states_path(':country_id'), dynamic_selectable_target: '#company_state_id' } } %>  
    
    <div class="form-row">
      <div class="form-group col-md-5">
        <%= form.label :state_id, "State or City" %> 
        <%= form.collection_select :state_id, @company.country.try(:states) || [], :id, :name, {prompt: "first choose country"}, {class: "form-control"} %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :town %>
        <%= form.text_field :town, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= form.label :zip %>
        <%= form.text_field :zip, class: "form-control" %>
      </div>
    </div>

    <%= form.label :address_line %>
    <%= form.text_area :address_line, class: "form-control" %>
    </div>
  </div>


  <div class="card mb-2">
    <h4 class="card-header">Add Person Connection</h4>
    <div class="card-body">
  <% if @company.connected.present? %>
    <%= form.nested_fields_for :connected do |cpf| %>
      <% person = cpf.object.person %>
      
      <div class="form-row">
        
        <div class="form-group col-md-6">
      <%= cpf.collection_select :person_id, policy_scope(Person.order(:first_name)), :id, :full_name, {prompt: "Choose..",include_blank: true },{class: "chosen-select"}  %>
        </div>
      
        <div class="form-group col-md-3">
        <%= cpf.select :position,options_for_positions ,{prompt: "Position..", include_blank: true},{class: "form-control"} %>
        </div>
      
        <div class="form-group col-md-3">
        <%= cpf.remove_nested_fields_link "Remove", class:"btn btn-outline-danger btn-md" %>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
    
  <div class="card-footer">
  <%= form.add_nested_fields_link :connected, "Add Connection", class: "btn btn-outline-primary btn-sm mt-2"%>
  </div>

</div>
<% if @company.new_record? %>
    <div class="card bg-primary text-white">
      <div class="card-body">
      <%= form.nested_fields_for :people, Person.new do |p_form|  %>
        <h4 class="card-title"> Add New Person</h4>
        <div class="form-row mb-2">      
        <%= p_form.hidden_field :user_id, value:current_user.id %>
        <div class="col-md my-1">
          <%= p_form.text_field :first_name, placeholder: "first name", class: "form-control" %>
        </div>
        <div class="col-md my-1">
          <%= p_form.text_field :middle_name, placeholder: "middle name", class: "form-control" %>
        </div>
        <div class="col-md my-1">
          <%= p_form.text_field :last_name, placeholder: "last name", class: "form-control" %> 
        </div>
        <div class="col-md my-1">
          <%= p_form.select :person_position, options_for_positions ,{prompt: "Position..", include_blank: true},{class: "form-control"} %> 
        </div>
        </div>
        <%= p_form.nested_fields_for :emails, Email.new do |e_form|  %>
          <%= render partial: "emails/emails", locals: {e_form: e_form} %>
        <% end %>
        
        <%= p_form.nested_fields_for :phones, Phone.new do |p_form| %>
          <%= render partial: "phones/phone", locals: {p_form: p_form} %>
        <% end %>
      <% end %>
      <p class="card-text">You can select person position after creation of person from companies form</p>
      </div>
      <div class="card-footer">
      <%= form.add_nested_fields_link :people, "Add Person", class: "btn btn-outline-light btn-sm"%>
      </div>
  </div>
  <% end #end of if record_new %>
    <%= form.submit class: 'btn btn-primary mt-2' %>
</div> 
<% end %>
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>

app/views/companies/_search_company.html.erb
<div id="accordion"> 
  <div class="card mb-2">

    <div class="card-header p-0" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="fales" aria-controls="collapseOne">
          Advanced Search
        </button>
      </h5>
    </div>


    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">

    <div class="card-body p-2">
      <%= search_form_for @search do |f| %>
        <div class="form-row">
          <div class="form-group col-md">
            <%= f.label :name_cont, "Company Name" %>
            <%= f.text_field :name_cont, class: "form-control" %>
          </div>
          <div class="form-group col-md">
            <%= f.label :id_eq, "Id" %>
            <%= f.text_field :id_eq, class: "form-control" %>
          </div>
          <div class="form-group col-md">
            <%= f.label :user_id_eq, "User" %>
            <%= f.collection_select :user_id_eq, policy_scope(User), :id, :alias, {include_blank: true, prompt: "Choose.."} ,class: "form-control" %>
          </div>
        </div>

      <div class="form-row">
        <div class="form-group col-md">
          <%= f.label :country_id_eq, "Country" %>
          <%= f.select :country_id_eq, options_for_select(countries_for.collect { |obj| [obj[:country_name] ,obj[:country_id]] }),{prompt:"Choose..", include_blank: true},  {class: "chosen-select" }  %>
        </div>
        <div class="form-group col-md">
          <%= f.label :state_id_eq, "State" %>
          <%= f.select :state_id_eq, options_for_select(states_for.collect { |sta| [sta[:state_name], sta[:state_id]]}),{prompt: "Choose..", include_blank: true}, {class: "chosen-select"} %>
        </div>
      </div>
      <%= f.submit "Search", class: "btn btn-outline-primary btn-sm"%>
    <% end %>
    </div>

    <div class="card-footer p-2 bg-light">
      <%= sort_link @search, :name, "Sort by Name", class: "btn btn-link"%>
      <%= sort_link @search, :id, "Sort by id",class: "btn btn-link" %>
    </div>
  
  </div>
  
  
  </div>
</div>

app/views/companies/edit.html.erb
<h1 class="text-center">Editing Company</h1>

<%= render 'form', company: @company %>
<div class="container my-3">
<%= link_to 'Show', @company, class: "btn btn-outline-info btn-sm" %> 
<%= link_to 'Back', :back, class: "btn btn-outline-info btn-sm"  %>
</div>

app/views/companies/import.html.erb
<h1>Import Companies</h1>
<div class="jumbotron">
    <%= form_tag import_companies_path,{class: "form-inline", multipart: true } do %>
      <div class="form-group">
      <%= label_tag :file,"CSV File" %>
      </div>
      <div class="form-group mx-3 mb-2">
      <%= file_field_tag :file, class: "form-control" %>
      </div>
      <%= submit_tag "import", class: "btn btn-primary btn-sm mb-2" %>
    <% end %>
</div>

app/views/companies/index.html.erb
<div class="container-fluid">
<h1 class="text-center">Companies (<%= @companies_count %>) </h1>
    <%= link_to fa_icon('folder-plus', type: :solid, text: 'New Company'), new_company_path, class: 'btn btn-dark btn-sm mb-2', :method => :get %>
    <%= link_to fa_icon('file-csv', type: :solid, text: "Import"), import_companies_path,class: "mb-2 btn btn-dark btn-sm", method: :get  %>
    <%= link_to fa_icon('file-csv', type: :solid, text: "Export"), companies_path(format: "csv"), class: "btn btn-dark btn-sm mb-2" %>
    <%= render "companies/search_company"  %>   

    <div class="row">
      <% @companies.each do |company| %>
        <div class="col-sm-6 col-md-4 col-lg-4 mb-2">
          <div class="card h-100">
            <div class="card-header">
              <div class="row">
                <div class="col-9">
                  <%= link_to company.name.capitalize.truncate(20), company, class: "card-title" %>
                </div>
                <div class="col-3">
                  <span class="badge"><%= company.id %></span>
                </div>
              </div>
            </div>
            <div class="card-body">
              <p class="text-center"> <%= image_tag company.logo_url(:logo) if company.logo? %> </p>
              <% company.people.each do |person|  %>
              <h6 class="card-subtitle mb-1"><%= link_to fa_icon('id-card', type: :regular, text: person.full_name.capitalize.truncate(16)), person %></h6> 
              <% end %>
              <small class="text-muted"> <%= company.state.name if company.state.present? %> <%= company.country.alpha2 if company.country.present? %> </small>
              <p class="card-text"><small class="text-muted">by <%= company.user.alias %> </small></p>
            </div>
            <div class="card-footer">
              <%= link_to fa_icon("edit", type: :regular), edit_company_path(company), class: 'card-link' if policy(company).update? %>
              <%= link_to fa_icon("trash-alt", type: :regular, style: "color:red"), company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-link float-right' if policy(company).destroy? %>
            </div>
          </div>
        </div>
          <% end %>
    </div>
      <div class="d-flex justify-content-center">
  <%= pagy_bootstrap_combo_nav_js(@pagy).html_safe %>
      </div>   
  </div>
  

app/views/companies/new.html.erb
<h1 class="text-center">New Company</h1>

<%= render 'form', company: @company %>
<div class="container" >
  <%= link_to 'Back', companies_path, class:"btn btn-outline-info btn-sm my-3" %>
</div>

app/views/companies/show.html.erb
<div class="container-fluid">
<div class="row">
 <div class="col<%= " col-12" if @company.logo.blank?  %>">
    <h2> <%= @company.name.mb_chars.titleize%></h2>
  </div>
  <div class="col-3">
    <%= image_tag @company.logo_url(:thumb), class: "img-fluid float-right d-block" if @company.logo?  %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-12">
    <div class="table-responsive-xs">
    <table class="table table-sm mt-2">
      <tbody>
        <tr>
          <th scope="row" class="table-light">Id</th>
          <td> <%= @company.id %></td>
        </tr>
        <tr>
          <th scope="row">Invoice Title</th>
          <td> <%= @company.invoice_title.mb_chars.titleize if @company.invoice_title.present? %></td>
        </tr>
        <tr>
          <th scope="row">Email</th>
          <td> <%= @company.email %></td>
        </tr>
        <tr>
          <th scope="row">Subscribed</th>
          <td>
          <% if @company.unsubscribe %>
            <%= fa_icon('user-slash', type: :solid) %>
          <% else %>
            <%= fa_icon('envelope-open-text', type: :solid) %>
          <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row">Url</th>
          <td><%= @company.url %></td>
        </tr>
        <tr>
          <th scope="row">Source</th>
          <td><%= @company.source %></td>
        </tr>
        <% if @company.phones.present? %>
          <% @company.phones.each do |phone| %>
        <tr>
          <th scope="row">Phone <%= phone.phone_type %></th>
          <td><%= number_to_phone(phone.phone_number, area_code: true, delimiter: " ") %></td>
        </tr>
          <% end %>
        <% end %>

      </tbody>
    </table>
  </div>
  </div>
  <div class="col-md-6 col-12">
    <div class="table-responsive-xs">
    <table class="table table-sm mt-2">
      <tbody>
        <tr>
          <th scope="row">Address</th>
          <td> <%= @company.address_title if @company.address_title.present? %></td>
        </tr>
        <tr>
          <th scope="row">Street</th>
          <td><%= @company.address_line.mb_chars.titleize if @company.address_line.present? %></td>
        </tr>
          <tr>
          <th scope="row">Town</th>
          <td><%= @company.town.mb_chars.capitalize if @company.town.present? %></td>
        </tr>
        <tr>
          <th scope="row">Zip</th>
          <td><%= @company.zip if @company.zip.present? %></td>
        </tr>
          <tr>
          <th scope="row">State/City</th>
          <td><%= @company.state.name if @company.state.present? %></td>
        </tr>
        <tr>
          <th scope="row">Country</th>
          <td><%= @company.country.name if @company.country.present? %></td>
        </tr>
        <tr>
          <th scope="row">Created by</th>
          <td> <%= @company.user.alias %></td>
        </tr>
        <tr>
          <th scope="row">Note</th>
          <td><%= @company.note.mb_chars.titleize if @company.note.present?%></td>
        </tr>
      </tbody>
    </table>
    </div>
  
  </div>
</div>

<div class="row">
  <div class="col-12">
  <% if @company.people.present? %>
    <h3> <%= "Person".pluralize(@company.people.count)%></h3>

    <div class="table-responsive-md">
    <table class="table">
      <caption>List of connected people</caption>
      <thead>
        <tr>
          <th scope="row">Full Name</th>
          <th scope="row">Position</th>
          <th scope="row">Phone</th>
        </tr>
      </thead>
      <tbody>
      <% @company.people.each do |person| %>
        <tr>
          <td> <%= link_to person.full_name.upcase, person %>   </td>
          <td> 
            <table class="table table-sm table-bordered">
            <% person.connected.where(company_id: @company.id ).each_with_index do |pcp| %> 
              <tr>
                <td> <%= pcp.position %> </td>
                <td>
                  <%= link_to fa_icon("link", type: :solid, style: "color: red"),
                              connected_path(pcp.id), method: :delete, data: { confirm: 'Are you sure?' },
                              class: 'fa-lg float-right' if policy(person).destroy? and pcp.position.present? %>
                </td>
              </tr>
            <% end %>
            </table>
          </td>
          
          
          <td>
          <table class="table table-bordered table-sm">
          <% person.phones.each do |phone| %> 
            <tr>
              <th scope="row"> <%= phone.phone_type %></th>
              <td>
              <%= number_to_phone(phone.phone_number, area_code: true, delimiter: " ") %>
              </td>
            </tr>
          <% end %>
          </table>
          </td>

        </tr>

        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
            
  </div>
</div>
  <div class="d-flex justify-content-md-start justify-content-sm-center">
  <%= link_to fa_stacked_icon("edit",text: "edit", type: "regular"), 
        edit_company_path(@company), class: "px-2" if policy(@company).update? %> 
  <%= link_to fa_stacked_icon('angle-left', text: "back"),
        session[:index_page_url] if session[:index_page_url].present?%>
  <%= link_to fa_stacked_icon('angle-left', text: "back to Companies"),
        companies_path if session[:index_page_url].blank?%>
  <%= link_to fa_stacked_icon("trash-alt",text: "Delete", type: :regular),
        @company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-link' if policy(@company).destroy? %>
  </div>
</div>