config/routes.rb
Rails.application.routes.draw do
  
  resources :machines do
    resources :pictures, only: [:new, :create, :destroy]
  end

  get 'connecteds/destroy'
  devise_for :users
  resources :users, only: [:index, :edit, :update, :show, :destroy]
  resources :connecteds, only: :destroy
  resources :categories, only:[:new, :create]


  get 'emails/index'
  get 'pages/home'
  get 'pages/dashboard'

  get :search, controller: :pages


  resources :people do
    collection do
      get :import
      post :import
    end
  end
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :companies, concerns: :paginatable do
    collection do
      get :import
      post :import
    end
  end
  
  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
  end
  

  root to: "pages#home"
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :brand
  belongs_to :category
  belongs_to :user
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank

  
  def title
    [self.brand.name, self.model_type].join(" ")
  end

  def brand_name
    brand.try(:name)
  end

  def brand_name=(name)
    self.brand = Brand.find_or_create_by(name: name.downcase.chomp) if name.present?
  end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
    @pictures = @machine.pictures.all
  end

  # GET /machines/new
  def new
    @machine = Machine.new
    @picture = @machine.pictures.build
  end

  # GET /machines/1/edit
  def edit
    @picture = @machine.pictures.build
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        if params[:pictures] != nil
          params[:pictures]["image"].each do |img|
          @picture = @machine.pictures.create!(:image => img, :machine_id => @machine.id)
          end
        end
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if params[:machine][:remove_picture].present?
        params[:machine][:remove_picture].each do |k,v|
          if v.to_i == 1
            @machine.pictures[k.to_i].destroy
          end
        end

      end
        if params[:pictures] != nil
          params[:pictures]["image"].each do |img|
          @picture = @machine.pictures.create!(:image => img, :machine_id => @machine.id)
          end
        end

      if @machine.update!(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:brand_name, :category_id, :model_type, :model_year, :condition, :price, :published, :user_id, {images: [ ]}, pictures_attributes: [:id, :image, :_destroy, :machine_id ]   )
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_with(model: machine, local: true) do |form| %>
  <% if machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :brand_name, class: "form-label" %>
    <%# form.collection_select :brand_id, Brand.all, :id, :name, {}, class: "chosen-select" %>
    <%= form.text_field :brand_name, data: {autocomplete_source: Brand.order(:name).map(&:name) },class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, {} , class: "selectize" %>
  </div>

  <div class="form-group">
    <%= form.label :model_type %>
    <%= form.text_field :model_type %>
  </div>

  <div class="form-group">
    <%= form.label :model_year %>
    <%= form.number_field :model_year %>
  </div>

  <div class="form-group">
    <%= form.label :condition %>
    <%= form.select :condition, ["new", "used"] %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="form-group">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  
  
  
  <div class="form-group">
    <%= form.fields_for :pictures, Picture.new do |p| %>
      <%= p.label :image, "picture" %>
      <%= p.file_field :image, multiple: true, name: "pictures[image][]" %>
    <% end %>

    <div class="form-group">
    <% @machine.pictures.each_with_index do |pic, i| %>
      <%= image_tag pic.image_url(:thumb) if pic.image_url.present?  %>
      <%= form.label :remove_picture, for: "remove_check#{i}" if pic.image.present? %>
      <%= form.check_box :remove_picture, name: "machine[remove_picture][#{i}]", id: "remove_check#{i}" if pic.image.present?   %>
    <% end %>                                                                       
    </div>
  </div>



  <div class="actions">
    <%= form.submit class: "btn btn-sm btn-dark" %>
  </div>
<% end %>


<div class="modal fade category-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="mySmallModalLabel">Add Category</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for Category.new do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :parent_id, class: "form-label" %>
            <%= f.select :parent_id,options_for_select(Category.all.collect{ |cat| [cat.name, cat.id] }) ,{include_blank: true} ,class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<div class="container-fluid">
  <h1>Machines</h1>
<%= link_to 'New Machine', new_machine_path %>
  <div class="row">
    <% @machines.each do |machine| %>
      <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
        <div class="card h-100 text-white bg-dark">
          <%= link_to(image_tag(machine.pictures[0].image_url(:medium), class: "card-img-top" ), machine ) if machine.pictures[0].present? %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to machine.title.titleize, machine, class: "text-white text-nowrap" %></h5>
              <p class="card-text">
                <% if machine.price.present? %>
                <%= number_to_currency(machine.price, delimiter: "." , unit: "€", precision: 0 ) %>
              <% else %>
                <%= link_to "Ask Price", new_user_session_path, class: "text-danger" %>
              <% end %>
              </p>
              <p class="card-text">
              condition : <%= machine.condition %>
              </p>
                
                
                
              
            
        <%= link_to 'Edit', edit_machine_path(machine), class: "text-white btn btn-sm btn-danger" %>
        <%= link_to fa_icon("trash-alt", type: :regular, style: "color:red"), machine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-link float-right' %>
            
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
  <% @machine.pictures.each_with_index do |pic, index| %>
    <%= image_tag pic.image_url(:medium) %>
  <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-12">
      <div class="table-responsive-xs">
        <table class="table table-sm mt-2">
          <tbody>
            <tr>                        
              <th scope="row" class="table-light">Article Number</th>
              <td><%= @machine.id %> </td>
            </tr>
            <tr>                        
              <th>Brand</th>
              <td><%= @machine.brand_name%> </td>
            </tr>
            <tr>                        
              <th>Category</th>
              <td><%= @machine.category.name %> </td>
            </tr>
            <tr>                        
              <th>Model Type</th>
              <td><%= @machine.model_type %> </td>
            </tr>
            <tr>                        
              <th>Model Year</th>
              <td><%= @machine.model_year %> </td>
            </tr>
            <tr>                        
              <th>  -----</th>
              <td>   </td>
            </tr>
          
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-6 col-12">
      <div class="table-responsive-xs">
        <table class="table table-sm mt-2">
          <tbody>
            <tr>                        
              <th scope="row" class="table-light">Price</th>
              <td><%= @machine.price %> </td>
            </tr>
            <tr>                        
              <th>By</th>
              <td><%= @machine.user.alias %> </td>
            </tr>
            <tr>                        
              <th>Published</th>
              <td><%= @machine.published%> </td>
            </tr>
            <tr>                        
              <th>Publish date</th>
              <td><%= @machine.created_at %> </td>
            </tr>
            <tr>                        
              <th>Model Year--</th>
              <td><%= @machine.model_year %> </td>
            </tr>
            <tr>                        
              <th>Condition</th>
              <td><%= @machine.condition %> </td>
            </tr>
          
          </tbody>
        </table>
    </div>
  </div>



<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>
</div>