config/routes.rb
Rails.application.routes.draw do
  
  resources :machines do
    resources :pictures, only: [:new, :create, :destroy]
  end

  get 'connecteds/destroy'
  devise_for :users
  resources :users, only: [:index, :edit, :update, :show, :destroy]
  resources :connecteds, only: :destroy
  resources :categories, only:[:new, :create]


  get 'emails/index'
  get 'pages/home'
  get 'pages/dashboard'

  get :search, controller: :pages


  resources :people do
    collection do
      get :import
      post :import
    end
  end
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :companies, concerns: :paginatable do
    collection do
      get :import
      post :import
    end
  end
  
  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
  end
  

  root to: "pages#home"
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<hr>
<footer class="page-footer font-small bg-dark text-white">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row" >

      <!-- Grid column -->
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="social text-center">
          <!-- Facebook -->
            <%= fa_icon "facebook",size: "2x", class: "p-2", type: :brand %>
          <!-- Whats App -->
            <%= fa_icon "whatsapp",size: "2x", class: "p-2", type: :brand %>
          <!-- Google +-->
            <%= fa_icon "google-plus-g",size: "2x", class: "p-2", type: :brand %>
          <!--Linkedin -->
            <%= fa_icon "linkedin",size: "2x", class: "p-2", type: :brand %>
          <!--Instagram-->
            <%= fa_icon "instagram",size: "2x", class: "p-2", type: :brand %>
          <!--Youtube-->
            <%= fa_icon "youtube",size: "2x", class: "p-2", type: :brand %>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"><small>
  All Rights Reserved by 314machine SPA © 2019 - <%= Time.now.year %>
    </small>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/"><%= fa_icon('servicestack',type: :brand)%>Machinist</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item active">
                <%= link_to 'Back', :back, class: "nav-link" %>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Index</a>


        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Companies", companies_path, :class => "dropdown-item"  %>
          <%= link_to "People", people_path, :class => "dropdown-item"  %>
          <%= link_to "Machines", machines_path, :class => "dropdown-item" %>
          <%= link_to "Emails", emails_index_path, :class => "dropdown-item" if current_user.emails.present? %>
          <div class="dropdown-divider"></div>
          <%= link_to "Users", users_path, :class => "dropdown-item"  %>
        </div> 
            </li>
          
          </ul>


          <div class="nav-item d-none d-lg-block">
          <%= form_with url: search_path, local: true, method: :get, html: {class: "form-inline my-2 my-lg-0"} do |form| %>
            <%= form.text_field :q, placeholder: "Search", class: "form-control form-control-sm mr-1", data: {behavior: "autocomplete"} %>
            <%= form.button fa_icon("search", type: :solid, class: "fa-md" ), class: "btn btn-sm btn-link text-white" %>
          <% end %>
          </div>

            <% if current_user %>
              
          <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to current_user.alias, users_path, method: :get, class: "nav-link disabled" if current_user.alias.present? %>
              </li>
              <li class="nav-item">
              <%= link_to fa_icon("sign-out-alt", type: :solid), destroy_user_session_path, method: :delete, class: "nav-link fa-lg" %>
              </li>

            <% else %>
              <li class="nav-item">
              <%# link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li>

            <li class="nav-item">
              <%= link_to ' Log in', new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        <% end %>
  </div>
</nav>

app/views/layouts/_search_bar.html.erb
<div class="pos-f-t d-lg-none">
<nav class="navbar navbar-light bg-light">
  <%= form_with url: search_path, local: true, method: :get, html: {class: "form-inline"} do |form| %>
    <%= form.text_field :q, placeholder: "Search", class: "form-control form-control-sm mr-sm-2", id: "search",data: {behavior: "autocomplete"}  %>
    
    <%= form.button fa_icon("search", type: :solid, class: "fa-lg" ), class: "btn btn-link text-dark my-2 my-sm-0" %>
  <% end %>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Machinist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="width:100%">
    <%= render "layouts/navbar" if user_signed_in? %>
    <% flash.each do |key, value| %>
      <div class="alert <%= flasherize(key)%>" role="alert"> <%= value %> </div>
    <% end %>
    <%= render "layouts/search_bar" if user_signed_in? %>

  
    <div class="container-fluid">
    <%= yield %>
    </div>
    <%= render "layouts/footer" if user_signed_in? %>
  </body>
</html>

app/views/layouts/pages_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Machinist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons", 'data-turbolinks-track': 'reload' %>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>